Make price field more clear [DO NOT MERGE]
blabno/bisq-ui pull request #167
Opened 2018-04-19 08:26 UTC by tkulpa

Why baseCurrencyCode and counterCurrencyCode sometimes are switched? Why btc is not always baseCurrency and when it should be other way around, for now sometimes tooltip is showed incorrectly

2018-04-23 07:33 UTC, blabno requested changes

2018-04-23 07:33 UTC, blabno commented on src/app/offers/offersList/offersList.component.ts
> +              private preferencesDAO: PreferencesDAO,) {
That comma is not required, I think.

2018-04-23 11:24 UTC, tborowy approved these changes

2018-04-25 13:49 UTC, blabno approved these changes

2018-04-25 13:49 UTC, merged