Feature/backups
blabno/bisq-ui pull request #188
Opened 2018-05-04 14:40 UTC by stychu

2018-05-07 07:04 UTC, tborowy requested changes

2018-05-07 07:04 UTC, tborowy commented on package.json
> +    "file-saver": "^1.3.8",
fix version

2018-05-08 07:28 UTC, tborowy approved these changes

2018-05-08 08:24 UTC, davvvid1 requested changes
Please, squash all commits because most of them are unnecessary considering this PR as a new feature.

e.g. "adjustments", "fix ...", "Initial changes..."

2018-05-08 08:57 UTC, davvvid1 approved these changes

2018-05-08 08:58 UTC, merged